1.2.0 Updates
nf-core/scnanoseq pull request #42
Opened 2024-12-24 05:21 UTC by atrull314

## PR Checklist

This PR contains the following updates for v1.2.0 of the pipeline:
- Adding oarfish as an additional quantifier
- Parallelization of isoquant by splitting on chromosome
- Upgrading isoquant
- Allowing read counts to utilize nanocount stats
- First pass at "modularizing" the pipeline by moving code to subworkflows

2025-01-03 17:31 UTC, lianov commented
@atrull314 : one thing I did just now catch is that we should disable `RSeQC` for outputs of the transcriptome aligned files. This process only works as intended with genome aligned files.

2025-01-08 13:22 UTC, itrujnara reviewed
Solid release, but I found some minor technical issues. I've also added some ideas to consider, feel free to argue with these.

2025-01-08 13:22 UTC, itrujnara commented on README.md
> -                params.barcode_format == "10X_3v3" ? "--kit-version 3v3" : params.barcode_format == "10X_5v2" ? "--kit-version 5v2" : ""
Is this information not required anymore?

2025-01-08 13:22 UTC, itrujnara commented on modules/local/merge_mtx.nf
> +    def args = task.ext.args ?: ''
Align equal signs

2025-01-08 13:22 UTC, itrujnara commented on modules/local/merge_mtx.nf
> +    """
Consider adding a stub, might be handy later

2025-01-08 13:22 UTC, itrujnara commented on modules/local/oarfish.nf
> +    """
Comments as in MTX_MERGE

2025-01-08 13:22 UTC, itrujnara commented on modules/local/split_fasta.nf
> +    awk '/^>/{chrom=(split(substr(\$0,2), a, " ")); filename=( a[1] ".split.fa"); print > filename; next}{print >> filename}' $fasta
Does this have to be a new module? Looks like the same result could be achieved with the `gawk` nf-core module

2025-01-08 13:22 UTC, itrujnara commented on nextflow_schema.json
> +                "quantifier": {
Is there a chance there will be more? This setup works as-is but it's not very scalable

2025-01-08 13:22 UTC, itrujnara commented on subworkflows/local/process_longread_scrna.nf
> +        if (quantifier.equals("oarfish")) {
Is the "both" option handled correctly here?

2025-01-08 13:22 UTC, itrujnara commented on subworkflows/local/process_longread_scrna.nf
> +    emit:
Harshil alignment

2025-01-08 13:22 UTC, itrujnara commented on subworkflows/local/umitools_dedup_split.nf
> +            SAMTOOLS_MERGE (
Versions from this one?

2025-01-08 13:22 UTC, itrujnara commented on subworkflows/local/umitools_dedup_split.nf
> +            SAMTOOLS_INDEX_MERGED( ch_dedup_single_bam )
And this?

2025-01-08 13:22 UTC, itrujnara commented on subworkflows/local/utils_nfcore_scnanoseq_pipeline/main.nf
> +        null
Is this null correct?

2025-01-08 15:41 UTC, atrull314 commented on README.md
> -                params.barcode_format == "10X_3v3" ? "--kit-version 3v3" : params.barcode_format == "10X_5v2" ? "--kit-version 5v2" : ""
Correct, we had modified the blaze module to base threads off `task.cpus` as is the case with other modules. This specific change was to resolve an error in documentation that we had put in before the change to the blaze module.

2025-01-08 19:44 UTC, atrull314 commented on subworkflows/local/process_longread_scrna.nf
> +        if (quantifier.equals("oarfish")) {
Yep! Its handled in a separate file to make sure they are able to run in parallel.

2025-01-08 21:00 UTC, atrull314 commented on modules/local/split_fasta.nf
> +    awk '/^>/{chrom=(split(substr(\$0,2), a, " ")); filename=( a[1] ".split.fa"); print > filename; next}{print >> filename}' $fasta
So the issue is the `gawk` nf-core module outputs as a single file, this awk statement is splitting a fasta into all of the chromosomes that compose it, so we need all the individual chromosome fastas as outputs. I'm not sure the module currently supports this behavior

2025-01-13 15:27 UTC, atrull314 commented on nextflow_schema.json
> +                "quantifier": {
That's a good point. I tried to resolve this with commit [d1f406e](https://github.com/nf-core/scnanoseq/pull/42/commits/d1f406e848beec300cc2525a07aba86773b6c57f). 

I made the parameter accept a comma-delimited list of values (have to be available quantifiers in the pipeline), and will also accept just a single quantifier.

2025-01-13 15:28 UTC, atrull314 commented on modules/local/merge_mtx.nf
> +    """
Should be resolved with commit [57258d7](https://github.com/nf-core/scnanoseq/pull/42/commits/57258d72dfa44d163a527976330146d7c783a49d)

2025-01-13 15:28 UTC, atrull314 commented on modules/local/oarfish.nf
> +    """
Should be resolved with commit [57258d7](https://github.com/nf-core/scnanoseq/pull/42/commits/57258d72dfa44d163a527976330146d7c783a49d)

2025-01-13 15:29 UTC, atrull314 commented on subworkflows/local/process_longread_scrna.nf
> +    emit:
Should be resolved with commit [6c6e7ec](https://github.com/nf-core/scnanoseq/pull/42/commits/6c6e7ec73b31f945d0709ca1f2786e94a0fc9d9e)

2025-01-13 15:30 UTC, atrull314 commented on modules/local/merge_mtx.nf
> +    def args = task.ext.args ?: ''
Should be resolved with commit [57258d7](https://github.com/nf-core/scnanoseq/pull/42/commits/57258d72dfa44d163a527976330146d7c783a49d)

2025-01-13 16:03 UTC, atrull314 commented on subworkflows/local/umitools_dedup_split.nf
> +            SAMTOOLS_MERGE (
Should be resolved with commit [67d0ab3](https://github.com/nf-core/scnanoseq/pull/42/commits/67d0ab375b3abe791e44560af2ec84f6d9897c0d)

2025-01-13 16:03 UTC, atrull314 commented on subworkflows/local/umitools_dedup_split.nf
> +            SAMTOOLS_INDEX_MERGED( ch_dedup_single_bam )
Should be resolved with commit [67d0ab3](https://github.com/nf-core/scnanoseq/pull/42/commits/67d0ab375b3abe791e44560af2ec84f6d9897c0d)

2025-01-13 16:03 UTC, atrull314 commented on subworkflows/local/utils_nfcore_scnanoseq_pipeline/main.nf
> +        null
I think this may have been a merge issue, but should be resolved with commit [9951f69](https://github.com/nf-core/scnanoseq/pull/42/commits/9951f69ac3d30b844aa167494d58fc141d316cba)

2025-01-13 16:06 UTC, atrull314 commented
> Solid release, but I found some minor technical issues. I've also added some ideas to consider, feel free to argue with these.

@itrujnara I think I have resolved all your points, please resolve them as you see fit or we can discuss alternative solutions. Thanks!

2025-01-15 09:53 UTC, itrujnara approved these changes
I see all the comments have been addressed, so good to go from my side. Good job!

2025-01-15 18:23 UTC, lianov requested changes

2025-01-15 18:23 UTC, lianov commented on workflows/scnanoseq.nf
> +            false
Disabling splitting the BAM in the transcriptomic data is currently creating a bottleneck at this step in regards to run time (BAM deduplication). This was originally solved in the genome mapping by splitting the BAM by chromosome, but due to the nature of the transcriptomic mappings, this cannot be enabled at this step as is.

@atrull314 and I are currently evaluating different approaches to implementing this optimization (or an alternative method), and once we have updated this portion of the workflow, the PR can move forward.

2025-02-19 14:48 UTC, atrull314 commented
> I see all the comments have been addressed, so good to go from my side. Good job!

Hi @itrujnara,

As @lianov mentioned we actually ended up finding an issue while we were performing validation of results that resulted in increased runtimes for our deduplication steps. I've kept the PR with the new changes so its easier to review, its available here https://github.com/nf-core/scnanoseq/pull/43. If you wouldn't mind taking a look when you have a chance.

Thanks,
Austyn

2025-02-21 17:12 UTC, lianov commented
@itrujnara : yes just adding a note here, that I the PR #43 is now approved but that we have not merged into dev yet as reviewing any other changes in that PR would likely be easier. It is all good from my end, and once it makes it to the dev branch and I can approve this one.

2025-02-28 16:25 UTC, atrull314 commented
Hi @itrujnara,

Just wanted to reach out again and ask if you wouldn't mind taking a look at PR https://github.com/nf-core/scnanoseq/pull/43 for the review.

Thanks,
Austyn

2025-03-03 10:30 UTC, itrujnara commented
Hi, 
sorry for the delay, I was quite busy last week. I've now left my comments on #43. Once they're addressed this one should be good to go as well.

2025-03-05 17:29 UTC, lianov commented
Adding a note here that all is good from my end pending the solution of the checks noted in the automated tests. @itrujnara : our understanding is that this is also good to to since you have reviewed PR #43, so feel free to approve this one as well. Thanks for the feedback.

2025-03-05 18:01 UTC, itrujnara approved these changes
No more doubts from my side, good to go 🚀

2025-03-18 17:15 UTC, merged